--(𓂀 𝕊𝕜𝕚 𝕙𝕦𝕓 𝕍𝟠.𝟜 𓂀)--
-- Made by 2ivsl discord
-- Made by majed
--- شكرا لاستخدامك للسكربت
-- تم صنع السكربت من قبل ماجد
if game.PlaceId == 9748064935 then
loadstring(game:HttpGet("https://raw.githubusercontent.com/M7majed/ScriptsByM7/main/BROOKHAVEN_arabic"))()
end
if game.PlaceId == 7346416636 then
loadstring(game:HttpGet("https://raw.githubusercontent.com/M7majed/ScriptsByM7/008ebbcc508a827d71a4a6005ff066f573fb49eb/RM7_LOL_MAJED.Lua"))()
end
if game.PlaceId == 335760407 then
loadstring(game:HttpGet("https://raw.githubusercontent.com/Majeedl12/ScriptsByM7/main/TpsStreetSoccer.RM7Hubs.Lua"))()
end
if game.PlaceId == 142823291 then
loadstring(game:HttpGet("https://raw.githubusercontent.com/M7majed/ScriptsByM7/main/MM2_OP.LUA"))()
end
if game.PlaceId == 574407221 then
loadstring(game:HttpGet("https://raw.githubusercontent.com/M7majed/ScriptsByM7/main/SuperHeroTycoon.LUA"))()
end


